# This is a basic workflow to help you get started with Actions

name: Multiple Jobs

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      run_apply:
        description: 'Run Terraform Apply'
        required: true
        default: false
        type: boolean
      run_destroy:
        description: 'Run Terraform Destroy'
        required: true
        default: false
        type: boolean
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'sandbox'
        type: choice
        options:
          - dev
          - test
          - uat
          - sandbox
          - prod
env:
  TF_WORKSPACE: ${{ inputs.environment || 'sandbox' }}
  TF_VAR_my_ssh_pub_key: ${{ secrets.MY_SSH_PUB_KEY }}
  #TF_WORKSPACE: ${{ inputs.environment }}
  # env.TF_WORKSPACE = inputs.environment
  # env.TF_WORKSPACE = inputs.environment or sandbox
jobs:
  plan:
    runs-on: ubuntu-latest #linux
    outputs:
      tfplan: ${{ steps.plan.outputs.tfplan }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Install / Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        id: plan
        run: |
          if [[ "${{ inputs.run_destroy }}" == "true" ]]; then
            terraform plan -destroy -var-file ${{ env.TF_WORKSPACE }}.tfvars -out=tfplan
          else
            terraform plan -var-file ${{ env.TF_WORKSPACE }}.tfvars -out=tfplan
          fi
          echo "tfplan=$(base64 < tfplan)" >> $GITHUB_OUTPUT
  destroy_or_apply:
    needs: plan_and_apply
    if: ${{ inputs.run_destroy }}
    runs-on: ubuntu-latest #linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install / Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        if: ${{ inputs.run_apply }}
        run: | 
          echo "${{ needs.plan_and_apply.outputs.tfplan }}" | base64 --decode > tfplan
          terraform apply tfplan

      